/*
 *************************************************************************
 ** argparse.h
 *************************************************************************
 ** Copyright (c) 1996  JP Software, All rights reserved
 *************************************************************************
 */

#ifndef ARGPARSE_H
#define ARGPARSE_H

char *NthArg(char *line, int index, char **argptr);

#endif  // ARGPARSE_H
