/*
 *************************************************************************
 ** iniistr.h
 *************************************************************************
 ** Copyright (c) 1997  JP Software, All rights reserved
 *************************************************************************
 */

#ifndef INIISTR_H
#define INIISTR_H

//#define FMT_FAR_PREC_STR  "%.*Fs"
//#define SLASHES           "\\/"
//#define BORDER            "Bor"
//#define FMT_INT           "%d"
//#define FMT_UINT          "%u"


// ISTRING.C
int ini_string(INIFILE *InitData, unsigned int *dataptr, char *string, int slen);


#endif  // INIISTR_H
