/*
 *************************************************************************
 ** option.h
 *************************************************************************
 ** Copyright (c) 1997  JP Software, All rights reserved
 *************************************************************************
 */

#ifndef OPTION_H
#define OPTION_H

// Return codes
#define RC_OK                 0
#define RC_PARM_ERROR         1
#define RC_SIG_ERROR          2
#define RC_BUILD_ERROR        3
#define RC_DIALOG_ERROR       4
#define RC_MEM_ERROR          5
#define RC_ARG_SYNTAX_ERROR   6
#define RC_ARG_BAD_DIRECTIVE  7
#define RC_MAX                8

#endif  // OPTION_H
