!topic
   ==> change to page break plus topic head and footnote tags

!wrap / nowrap
   ==> set flag for paragraph breaks

!noindex and others
   ==> discard

italic (), bold (),and caution ()
   ==> replace with simple tags for macro

links (, )
   ==> replace with tags for macro

!indent
   ==> replace with style tags for macro

escape ()
   ==> replace with field, or tags for macro

symbols (, others?)
   ==> replace with equivalent, field, or tags for macro

